language: ruby
rvm:
  - ruby-head
before_install:
  - gem install bundler

bundler_args: --without development

before_script:
  - psql -c 'create database community_test;' -U postgres

script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate test
